### ISSUE TITLE
Daylight Coefficient Image Based Error

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-analysis-tools/honeybee-plus#31]
Hi @mostaphaRoudsari 

After trying out the sample file  of DC Image Based using the sky matrix, the following error comes up:
![capture](https://cloud.githubusercontent.com/assets/21184323/21542760/89a64ae6-cdc0-11e6-9e6d-dfe004dcae18.PNG)

I have been trying out with three different epw, still in vain.

**Comment by mostaphaRoudsari** [comment]
Hi @DambronOlivier, the error is happening because for some reason the images are not created, or created with a different name and the component fails to find and rename them. Can you open the component and comment [these lines](https://github.com/ladybug-analysis-tools/honeybee-plus/blob/master/plugin/grasshopper/src/HoneybeePlus_Run%20Radiance%20Analysis.py#L69-L73) and see what will be the output.

**Comment by mostaphaRoudsari** [comment]
Hi @DambronOlivier, Did you have the file from an earlier study open? The error message has a Windows Error. I will add a catch for this to give a warning instead of crashing.

**Comment by mostaphaRoudsari** [comment]
This should be fixed now. Thanks @DambronOlivier for reporting the issue.

**Comment by DambronOlivier** [comment]
Hi @mostaphaRoudsari ,
Thanks for all the updates.

I still do get a permission issue. 
![capture5](https://cloud.githubusercontent.com/assets/21184323/22060848/72f8be6e-dd6a-11e6-9842-744d09951923.PNG)

I have tried to change the permissions to the whole folder C:\Ladybug and this comes up:
![capture6](https://cloud.githubusercontent.com/assets/21184323/22061004/f8d86354-dd6a-11e6-8015-e127da033296.PNG)

**Comment by mostaphaRoudsari** [comment]
@DambronOlivier thanks for testing the updated version. At least it doesn't crash!

Hmm. 1KB hdr file shows that the file is corrupted but that shouldn't make a difference for renaming. Try to run the script below and let's see if you get the similar error. Is the 001 image also 1KB?

In the image-based analysis `results` just collect the path to the images in the folder so that shouldn't be the problem.

```python
import os

fp = r'c:\ladybug\workshop\imagebased_daylightcoeff\results'
hdrs = (f for f in os.listdir(fp) if f.lower().endswith('.hdr'))
for f in hdrs:
    os.rename(os.path.join(fp, f), os.path.join(fp, f + '_renamed'))
```

**Comment by mostaphaRoudsari** [comment]
I can recreate the error on Windows 10! I'll keep you posted.
![image](https://cloud.githubusercontent.com/assets/2915573/22066027/ee5d11fc-dd58-11e6-84ea-0f863f89b404.png)

**Comment by mostaphaRoudsari** [comment]
Here is what makes the hdr files for matrices corrupt. I assume these issues are coming from the same source.
![image](https://cloud.githubusercontent.com/assets/2915573/22066790/9823eff0-dd5c-11e6-9a01-65d669c3a117.png)

**Comment by mostaphaRoudsari** [comment]
@DambronOlivier this issue turns out to be deep down in calculating view size in Radiance. It was happening since you were trying a non-square view. This should be fixed now. Update honeybee libraries, close Rhino and re-run the grasshopper definition. Make sure to set reuse daylightMTX to False so it overwrites the current failed hdrs.
![image](https://cloud.githubusercontent.com/assets/2915573/22132648/44ad14fe-de89-11e6-9905-540f61600a8b.png)

**Comment by DambronOlivier** [comment]
@mostaphaRoudsari 
Wonderful!
