### ISSUE TITLE
How to debug code in Honeybee and Honeybee plus external libraries?

### ISSUE THREAD

**Issue by antonszilasi** [ladybug-analysis-tools/honeybee-plus#33]
@mostaphaRoudsari 

Perhaps I'm missing something here but reloading modules both in the Rhino EditPythonScript and Grasshopper python scripts (Since they are both the same environment with the same sys.modules()) doesn't seem to work at least not consistently.

The only consistent way is to close Rhino and open it thereby loading the modules from scratch but this is really slow, so how did you go about writing and testing your code? 

Also I'm using traceback which seems to work well, is this what you used? 

Thanks!

**Comment by chriswmackey** [comment]
@antonszilasi ,
You should be using [Atom](https://atom.io/) to edit code along with the [Atom Script package](https://atom.io/packages/script) and standalone [Python 2.7](https://www.python.org/downloads/) to run the code.  
-Chris

**Comment by mostaphaRoudsari** [comment]
@antonszilasi you need to reload the module. Grasshopper caches the libraries once imported. That's why you won't see the updates. Let's say you have changed something in `hbsurface` then you need to do:

```python
import honeybee
reload(honeybee.hbsurface)
#  your code here
```

**Comment by chriswmackey** [comment]
That also works.  Thanks for that, @mostaphaRoudsari .  It will make things a lot easier when working in the GH interface.

**Comment by mostaphaRoudsari** [comment]
@antonszilasi and @chriswmackey, to make sure that you load and change the code from the folder that is synced to GitHub use butterfly component. makes sure it is imported from the right location. Otherwise butterfly will be loaded from the installation folder.

![image](https://cloud.githubusercontent.com/assets/2915573/21750567/03dc9b24-d584-11e6-9fcc-ce93cb588f8c.png)

@antonszilasi I think we can close this now?
